# Generated by Django 3.1 on 2020-08-10 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('center', models.CharField(max_length=100)),
                ('employee_id', models.CharField(max_length=6)),
                ('building', models.CharField(max_length=100)),
                ('faculty', models.CharField(max_length=100)),
                ('level', models.IntegerField()),
                ('department', models.CharField(max_length=100)),
                ('rank', models.CharField(max_length=100)),
            ],
        ),
    ]
