# Generated by Django 3.1 on 2020-08-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='building',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='center',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='employee_id',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='faculty',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='rank',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
