# Generated by Django 3.1 on 2020-08-19 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_auto_20200814_2307'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYearSemester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.IntegerField(default=1)),
                ('academic_semester', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_no', models.CharField(max_length=2)),
                ('student_count', models.IntegerField(blank=True, null=True)),
                ('generated_group', models.CharField(blank=True, max_length=100, null=True)),
                ('academic_year_semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.academicyearsemester')),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programme_name', models.CharField(max_length=100)),
                ('programme_abbv', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=25)),
                ('color', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Subgroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subgroup_no', models.IntegerField(default=1)),
                ('generated_subgroup', models.CharField(blank=True, max_length=100)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.group')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.programme'),
        ),
    ]
