# Generated by Django 3.1 on 2020-08-17 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_auto_20200814_2307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offeredYear', models.CharField(blank=True, max_length=4)),
                ('offeredSemester', models.CharField(blank=True, max_length=100)),
                ('subjectName', models.CharField(blank=True, max_length=100)),
                ('subjectCode', models.CharField(blank=True, max_length=10)),
                ('noLecHours', models.IntegerField(blank=True, null=True)),
                ('noTutHours', models.IntegerField(blank=True, null=True)),
                ('noLabHours', models.IntegerField(blank=True, null=True)),
                ('noEveHours', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
