# Generated by Django 3.0.8 on 2020-09-06 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_building_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
