# Generated by Django 3.1 on 2020-08-20 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_workingdays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingdays',
            name='endtime',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workingdays',
            name='starttime',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
