# Generated by Django 3.1 on 2020-09-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_auto_20200909_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='programme_abbv',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
