# Generated by Django 3.1 on 2020-09-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_auto_20200910_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyearsemester',
            name='academic_details',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
