# Generated by Django 3.1 on 2020-09-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0006_academicyearsemester_academic_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicyearsemester',
            name='academic_details',
            field=models.CharField(default='Error', max_length=6),
        ),
    ]
