# Generated by Django 3.1 on 2020-09-11 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0008_auto_20200910_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicyearsemester',
            name='academic_details',
        ),
    ]
