# Generated by Django 3.1 on 2020-09-11 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0009_remove_academicyearsemester_academic_details'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='academicyearsemester',
            constraint=models.UniqueConstraint(fields=('academic_year', 'academic_semester'), name='academic_details'),
        ),
        migrations.AlterModelTable(
            name='academicyearsemester',
            table='academicyearsemester',
        ),
    ]
