# Generated by Django 3.1 on 2020-09-11 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0010_auto_20200911_0833'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='academicyearsemester',
            table=None,
        ),
    ]
