# Generated by Django 3.1 on 2020-09-11 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0013_auto_20200911_0937'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subgroup',
            constraint=models.UniqueConstraint(fields=('group', 'subgroup_no'), name='subgroup_details'),
        ),
    ]
