# Generated by Django 3.1 on 2020-09-12 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_subjects'),
        ('timetable', '0015_auto_20200911_1751'),
    ]

    operations = [
    ]
