# Generated by Django 3.1 on 2020-09-12 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0016_merge_20200912_1009'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='academicyearsemester',
            table='timetable_academicyearsemester',
        ),
    ]
