# Generated by Django 3.1 on 2020-09-18 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0017_auto_20200912_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.group')),
                ('lecturers', models.ManyToManyField(to='timetable.Lecturer')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.subjects')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.tags')),
            ],
        ),
    ]
