# Generated by Django 3.1 on 2020-09-18 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0018_session'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='group',
            new_name='group_id',
        ),
    ]
