# Generated by Django 3.1 on 2020-09-18 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0019_auto_20200918_1153'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Session',
        ),
    ]
