# Generated by Django 3.1 on 2020-09-18 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0021_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='duration',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='session',
            name='student_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='session',
            name='subgroup_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable.subgroup'),
        ),
    ]
