# Generated by Django 3.1 on 2020-09-18 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0022_auto_20200918_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='subgroup_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable.subgroup'),
        ),
    ]
