# Generated by Django 3.1 on 2020-09-18 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0023_auto_20200918_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeslots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='consecutive_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable.session'),
        ),
        migrations.CreateModel(
            name='ParallelSession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sessions', models.ManyToManyField(to='timetable.Session')),
            ],
        ),
        migrations.CreateModel(
            name='NonParallelSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessions', models.ManyToManyField(to='timetable.Session')),
            ],
        ),
    ]
