# Generated by Django 3.0.8 on 2020-09-23 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0024_auto_20200918_1646'),
        ('timetable', '0005_auto_20200906_0834'),
    ]

    operations = [
    ]
