# Generated by Django 3.1 on 2020-09-29 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0024_auto_20200918_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parallelsession',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
