# Generated by Django 3.1 on 2020-10-01 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0025_auto_20200929_0911'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockWorkingDays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nubdays', models.IntegerField(blank=True, null=True)),
                ('days', models.CharField(blank=True, max_length=255, null=True)),
                ('starttime', models.CharField(blank=True, max_length=255, null=True)),
                ('endtime', models.CharField(blank=True, max_length=255, null=True)),
                ('slot', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SessionBlockedTimeslots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
                ('starttime', models.CharField(max_length=50)),
                ('endtime', models.CharField(max_length=50)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.session')),
            ],
        ),
        migrations.CreateModel(
            name='LecturerBlockedTimeslots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
                ('starttime', models.CharField(max_length=50)),
                ('endtime', models.CharField(max_length=50)),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.lecturer')),
            ],
        ),
        migrations.CreateModel(
            name='GroupBlockedTimeslots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
                ('starttime', models.CharField(max_length=50)),
                ('endtime', models.CharField(max_length=50)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.group')),
                ('subgroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable.subgroup')),
            ],
        ),
    ]
