# Generated by Django 3.1 on 2020-10-02 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0026_groupblockedtimeslots_lecturerblockedtimeslots_mockworkingdays_sessionblockedtimeslots'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsecutiveSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consecutivesession_session1', to='timetable.session')),
                ('session2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consecutivesession_session2', to='timetable.session')),
            ],
        ),
        migrations.DeleteModel(
            name='Timeslots',
        ),
        migrations.AddConstraint(
            model_name='consecutivesession',
            constraint=models.UniqueConstraint(fields=('session1', 'session2'), name='consecutive_details'),
        ),
    ]
