# Generated by Django 3.0.8 on 2020-09-28 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0028_lecturerroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturerroom',
            name='building',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable.Building'),
        ),
    ]
