# Generated by Django 3.0.8 on 2020-10-03 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0033_sessionroom'),
        ('timetable', '0004_auto_20200820_1842'),
        ('timetable', '0027_auto_20201002_0956'),
    ]

    operations = [
    ]
