# Generated by Django 3.0.8 on 2020-10-03 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0034_merge_20201003_0518'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsecutiveSessionRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable.Building')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.Room')),
                ('session1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session1', to='timetable.Session')),
                ('session2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session2', to='timetable.Session')),
            ],
        ),
    ]
